version: '3'
services:
  database:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ESP
      MYSQL_ROOT_HOST: "%"
    volumes:
      - /var/docker/esp/mysql:/var/lib/mysql
  esp:
    build: .
    restart: always
    ports:
      - "127.0.0.1:5010:8080"
    volumes:
      - /var/log/esp:/logs
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER_NAME=root
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}