spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/esp
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update