apiVersion: v1
kind: Service
metadata:
  name: esp-controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  selector:
    app: esp-controller
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080